initial charm-cloudkitty version
openstack-charmers/charm-cloudkitty pull request #1
Opened 2022-08-08 03:03 UTC by hernandanielg

Initial cloudkitty charm version

This version is able to:
- installs required packages
- render config in configuration file

2022-08-12 19:20 UTC, camille-rodriguez commented on charmcraft.yaml
> +        channel: "20.04"
Should we test this right away with 22.04 ? Since the point release came out, I would expect that the first cloud where we would deploy cloudkitty would be Yoga/22.04

2022-08-12 19:21 UTC, camille-rodriguez commented on src/charm.py
> +            # self, "cloudkitty",
lines 70-75 comments seem duplicated from lines 61-66

2022-08-12 19:22 UTC, camille-rodriguez commented on src/charm.py
> +        This event happens when n IdentityService relation is added to the
when "n" ?

2022-08-12 19:34 UTC, ajkavanagh commented on charmcraft.yaml
> +        channel: "20.04"
We're still validating 22.04 (jammy) at the moment; upstream is a bit of a mixed bag as they didn't actually validate yoga on python 3.10 (only on 3.8 and 3.9).  However, we do intend to have a full validation of the OpenStack charms/yoga on jammy either prior or alongside the zed release.

Back to your question, yes, we should definitely include 22.04.  Also we ought to also run on the additional architectures:

```yaml
architectures: [amd64, s390x, ppc64el, arm64]
```

2022-08-31 23:02 UTC, wolsen commented on charmcraft.yaml
> +        channel: "20.04"
100% agree, this should only be targeted towards 22.04/Yoga and newer. However, during development its going to be a bit faster progress on Focal (and then shifting to jammy soon) so as not to worry about some of the jammy pieces.

2022-08-31 23:28 UTC, wolsen requested changes

2022-08-31 23:28 UTC, wolsen commented on src/charm.py
> +        relation_set(
As discussed, this is from charmhelpers and using the classic charm style. You should be using operator framework conventions to set the data (which is essentially just updating a dictionary).

Please refer to [the documentation on juju relations](https://juju.is/docs/sdk/relations) for information.

2022-09-15 17:10 UTC, wolsen requested changes
Please check the pep8 compliance in addition to the comments in the test cases.

2022-09-15 17:10 UTC, wolsen commented on unit_tests/test_charm.py
> +    def test_on_install(self, log, mock_call):
This is testing at the wrong level. You don't want to have to mock way down into the charmhelpers layers if you can avoid it. Since you're using the charm-ops-openstack library, you should be able to mock `ops_openstack.core.apt_update` and `ops_openstack.core.apt_install` to validate that they are being called with the correct paramters.

2022-09-15 17:10 UTC, wolsen commented on unit_tests/test_charm.py
> +    def test_config_changed(self, fchown, chown, getpwnam):
This is also at too low of a level. You don't use these modules and in reality that are in dependent libraries that exist. At a higher level, this is a problem because your tests are dependent on a specific implementation of a function that you are depending on. When using a library you are depending on it to provide some functionality, but you want to avoid depending on it using *specific* functionality and working that into your test cases.

This needs to be reworked to focus on the logical changes that you expect to happen and the specific function that the charm does (not what its dependencies do).

2022-09-16 22:39 UTC, wolsen approved these changes
I did not identify this previously (but should have). This change is lacking code-level documentation (i.e. docstrings). To minimize the future delta, I will merge. However, please follow this patch with a docstring patch.

Overall this change has come a long way and is looking quite positive.

2022-09-16 22:39 UTC, merged