add documentation in README.md
openstack-charmers/charm-cloudkitty pull request #3
Opened 2022-09-21 20:53 UTC by hernandanielg

2022-09-22 18:53 UTC, camille-rodriguez commented
Should we add a TO-DO section to highlight the missing pieces until the charm is stable ? @wolsen

2022-09-23 15:22 UTC, wolsen commented
> Should we add a TO-DO section to highlight the missing pieces until the charm is stable ? @wolsen

I think this makes a lot of sense to add the TODO section so its clear what is not yet completed.

2022-09-23 15:22 UTC, wolsen commented on README.md
> +Add cloudkitty charm required relations
This is just a list of relations, which isn't as helpful as it could be. If we're going to document the relations, let's provide some information about what the relation provides.

2022-09-23 15:22 UTC, wolsen commented on README.md
> +This charm provides a way to deploy Cloudkitty - Openstack Rating as a Service module - in Openstack
Can we expand on what cloudkitty is for those who are not aware of what it is? Just a bit. I don't think we're trying to document cloudkitty, but what deploying this charm provides.

2022-09-29 21:18 UTC, hernandanielg commented on README.md
> +Add cloudkitty charm required relations
Updated it ;) thanks

2022-09-29 21:18 UTC, hernandanielg commented on README.md
> +This charm provides a way to deploy Cloudkitty - Openstack Rating as a Service module - in Openstack
I have added a brief about cloudkitty

2022-09-29 23:28 UTC, wolsen requested changes

2022-09-29 23:28 UTC, wolsen commented on README.md
>  `CONTRIBUTING.md` for developer guidance.
This is boiler plate from the Juju charm init. It would be helpful to mention this text for guidelines on how to contribute via Juju, however it would also be good to provide a link to https://docs.openstack.org/charm-guide/latest/community/software-contrib/index.html. I do not have a good example of where this might be mentioned.

2022-09-29 23:28 UTC, wolsen commented on README.md
> +MySQL relation - provides database storage for the cloudkitty service.
I think we should probably have a note indicating that this is not the mysql-innodb-cluster charm.

2023-05-15 15:08 UTC, closed without merging