added gnocchi relation
openstack-charmers/charm-cloudkitty pull request #4
Opened 2022-09-21 21:40 UTC by hernandanielg

2022-09-22 22:17 UTC, freyes requested changes
Hi Hernan,

Thanks for implementing support for Gnocchi, I left some inline comments.

2022-09-22 22:17 UTC, freyes commented on metadata.yaml
> +    interface: gnocchi
:+1:

2022-09-22 22:17 UTC, freyes commented on src/test_utils.py
> +def add_base_metric_service_relation(harness: Harness) -> str:
harness.add_relation() returns an `int`, not a `str`.

2022-09-22 22:17 UTC, freyes commented on src/test_utils.py
> +def add_complete_metric_relation(harness: Harness) -> None:
the return type should be `int` and not `None`.

2022-09-22 22:17 UTC, freyes commented on templates/cloudkitty.conf
> +{% if metric_service -%}
I believe this should check for `metric_service.gnocchi_url` instead since `metric_service` will always evaluate to True since it is a reference to an instance of the class `GnocchiRequires`

2022-09-23 22:31 UTC, hernandanielg commented on src/test_utils.py
> +def add_base_metric_service_relation(harness: Harness) -> str:
good catch thanks!

2022-09-23 22:32 UTC, hernandanielg commented on templates/cloudkitty.conf
> +{% if metric_service -%}
you're so right, I was facing this issue when relation emits ready event but gnocchi_url wasn't ready

2022-09-24 03:14 UTC, wolsen approved these changes

2022-09-25 12:50 UTC, freyes approved these changes
LGTM. Thanks for addressing the comments, Hernan ;-)

2022-09-25 12:50 UTC, merged