added db migration
openstack-charmers/charm-cloudkitty pull request #5
Opened 2022-09-21 22:05 UTC by hernandanielg

2022-09-23 15:25 UTC, wolsen requested changes
Unit tests?

2022-09-23 15:25 UTC, wolsen commented on src/charm.py
> +    def migrate_database(self):
Missing docstrings. Is there a reason this is a public method vs a private (prefixed by _) ? I'm not sure what the appropriate one is there.

2022-09-23 15:25 UTC, wolsen commented on src/charm.py
> +    def _on_database_created(self, event):
docstrings

2022-09-27 15:44 UTC, freyes requested changes
Hi Hernan, added some inline comments.

2022-09-27 15:44 UTC, freyes commented on src/charm.py
> +            subprocess.run(cmd, capture_output=True)
the docstring of this method says that if the dbsync fails the unit gets into error state, although the exit code returned by subprocess.run() is not being managed in any way. If you are expecting that subprocess raises an exception when the command fails I suggest you to use `subprocess.check_call()` instead.

2022-09-27 15:44 UTC, freyes commented on src/charm.py
> +    def _render_config(self, event) -> str:
what do you need the `event` argument for?

2022-09-27 15:44 UTC, freyes commented on templates/cloudkitty.conf
> +version = 1
why is the version set to `1` while the default is `2`?

2022-09-27 15:51 UTC, hernandanielg commented on src/charm.py
> +    def _render_config(self, event) -> str:
I was saving it for the future - in the render config function we need to check if all relations are ok before rendering so in case is not ready we can use the event to defer it

2022-09-27 15:53 UTC, hernandanielg commented on templates/cloudkitty.conf
> +version = 1
in this initial version of cloudkitty charm we're using storage version 1 to use sqlalchemy driver, for version 2 we need to use influxdb so I think that's for the next charm cycle

2022-09-27 15:55 UTC, hernandanielg commented on src/charm.py
> +            subprocess.run(cmd, capture_output=True)
ok let me change it to `subprocess.check_call()`

2022-09-27 18:04 UTC, freyes requested changes

2022-09-27 18:04 UTC, freyes commented on src/charm.py
> +    def _render_config(self, event) -> str:
ack

2022-09-27 18:04 UTC, freyes commented on src/charm.py
> +            subprocess.check_call(cmd, capture_output=True)
check_call doesn't support the `capture_output` argument.

```In [1]: import subprocess

In [2]: subprocess.check_call(['ls'], capture_output=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-65f61be402fa> in <module>
----> 1 subprocess.check_call(['ls'], capture_output=True)

/usr/lib/python3.10/subprocess.py in check_call(*popenargs, **kwargs)
    362     check_call(["ls", "-l"])
    363     """
--> 364     retcode = call(*popenargs, **kwargs)
    365     if retcode:
    366         cmd = kwargs.get("args")

/usr/lib/python3.10/subprocess.py in call(timeout, *popenargs, **kwargs)
    343     retcode = call(["ls", "-l"])
    344     """
--> 345     with Popen(*popenargs, **kwargs) as p:
    346         try:
    347             return p.wait(timeout=timeout)

TypeError: Popen.__init__() got an unexpected keyword argument 'capture_output'

```

2022-09-27 18:04 UTC, freyes commented on unit_tests/test_charm.py
> +    @patch('subprocess.check_call')
I suggest to use `@patch('subprocess.check_call', autospec=True)`, see https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch for details on what it does.

2022-09-27 21:27 UTC, hernandanielg commented on src/charm.py
> +            subprocess.check_call(cmd, capture_output=True)
not sure why unit test was not failing before, I have fixed it thanks! good catch

2022-09-27 22:57 UTC, wolsen requested changes

2022-09-27 22:57 UTC, wolsen commented on src/charm.py
> +            On this function we handle the execution of
bit of a nit, but the body text here should be aligned with the """ - so basically 4 spaces less.

2022-09-27 22:57 UTC, wolsen commented on unit_tests/test_charm.py
> +        _check_call.assert_has_calls(calls, any_order=True)
Why is `any_order=True` here? Is it truly acceptable for the commands to be run in any order? If so that's fine.

2022-09-27 22:57 UTC, wolsen commented on unit_tests/test_charm.py
> +        content = self.harness.charm._render_config('An event')
While this parameter is ignored, the string 'An event' isn't really close to the final option here. It should probably be a mock object rather than a string.

2022-09-27 23:57 UTC, hernandanielg commented
Hello @wolsen I have made changes according to your suggestions - Thanks!

2022-09-28 00:02 UTC, wolsen approved these changes
LGTM thanks!

2022-09-28 00:02 UTC, merged